name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ✅ Checkout source code
      uses: actions/checkout@v3

    - name: ✅ Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: ✅ Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: ✅ Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: 🐳 Build Docker image
      run: |
        docker build -t php-ci-cd-app .
        docker tag php-ci-cd-app:latest ${{ secrets.ECR_REPO }}:latest

    - name: 🚀 Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_REPO }}:latest

    - name: 🧠 SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
        organization: ${{ secrets.SONAR_ORGANIZATION }}
        projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: 🛰️ Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster php-ci-cd-cluster \
          --service php-app-service \
          --force-new-deployment \
          --region ${{ env.AWS_REGION }}
